#!/usr/bin/env python

import argparse
import json
import os
import pathlib
import platform
import re
import shutil
import stat
import textwrap


RE_MSVC_VERSION = re.compile(r"msvc([0-9]+)[^0-9]*([0-9]+)?\S*")

def msvc_sort_key(v: str) -> (int, int):
    m = RE_MSVC_VERSION.match(v)
    if not m:
        raise ValueError(f"{m} has unsupported version")
    return (int(m.group(1)), int(m.group(2) or 0))


ROOT = pathlib.Path(__file__).resolve().parent
TOOLCHAINS = [p.stem for p in (ROOT / "envs").iterdir() if p.suffix == ".json"]
TOOLCHAINS.sort(key=msvc_sort_key)

def main():
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument("--toolchain", choices=TOOLCHAINS, required=True, help="MSVC toolchain version")
    parser.add_argument("location", type=pathlib.Path, default=pathlib.Path.cwd(), nargs="?",help="Directory")
    args = parser.parse_args()

    with (ROOT / "envs" / f"{args.toolchain}.json").open("r") as f:
        toolchain_json = json.load(f)

    vcvars_path = args.location / "VC/Auxiliary/Build/vcvarsall.bat"
    vcvars_path.parent.mkdir(exist_ok=True)

    def path_list_to_cmd_variable(rel_paths: list[str]) -> str:
        result = ";".join("%__MSVC_ROOT%\\" + p.replace("/", "\\") for p in rel_paths)
        return result

    path_env = path_list_to_cmd_variable(toolchain_json["winepath"])
    inc_env = path_list_to_cmd_variable(toolchain_json["include"])
    lib_env = path_list_to_cmd_variable(toolchain_json["lib"])
    msvc_version = toolchain_json["version"]

    vcvarsall_contents = textwrap.dedent(f"""\
        @echo off
        
        rem This file is autogenerated. Changes will be lost.
        
        set __VCVARSALL_TARGET_ARCH=
        set "__VCVARSALL_ARGS_LIST=%*"
        
        call :parse_loop
        
        if "%__VCVARSALL_TARGET_ARCH%" == "" (
        goto :usage_error
        )
        
        set __MSVC_ROOT=%~dp0..\\..\\..
        for %%i in ("%__MSVC_ROOT%") do SET "__MSVC_ROOT=%%~fi"
        
        @echo [vcvarsall.bat] Environment initialized for: 'x86'
        
        set PATH={path_env};%PATH%
        set INCLUDE={inc_env};%INCLUDE%
        set LIB={lib_env};%LIB%
        set VisualStudioVersion={msvc_version}
        
        
        :parse_loop
        for /F "tokens=1,* delims= " %%a in ("%__VCVARSALL_ARGS_LIST%") do (
            call :parse_argument %%a
            set "__VCVARSALL_ARGS_LIST=%%b"
            goto :parse_loop
        )
        
        exit /B 0
        
        :parse_argument
        
        set __local_ARG_FOUND=
        if /I "%1"=="x86" (
        set __VCVARSALL_TARGET_ARCH=x86
        set __local_ARG_FOUND=1
        )
        @REM  CLion requires amd64 support, so fake it
        if /I "%1"=="amd64" (
            set __VCVARSALL_TARGET_ARCH=amd64
            set __local_ARG_FOUND=1
        )
        if "%__local_ARG_FOUND%" NEQ "1" (
            if "%2"=="" (
                @echo [ERROR:%~nx0] Invalid argument found : %1
            ) else (
                @echo [ERROR:%~nx0] Invalid argument found : %1=%2
            )
        )
        set __local_ARG_FOUND=
        exit /B 0
        
        :usage_error
        
        echo [ERROR:%~nx0] Error in script usage.
        
        :end
        set __VCVARSALL_TARGET_ARCH=
        set __VCVARSALL_ARGS_LIST=
        set __MSVC_ROOT=
    """)
    with vcvars_path.open("w", newline="\n") as f:
        f.write(vcvarsall_contents)


if __name__ == "__main__":
    raise SystemExit(main())
