#!/usr/bin/env python

import argparse
import json
import os
import pathlib
import platform
import re
import shutil
import stat
import textwrap


RE_MSVC_VERSION = re.compile(r"msvc([0-9]+)[^0-9]*([0-9]+)?\S*")

def msvc_sort_key(v: str) -> (int, int):
    m = RE_MSVC_VERSION.match(v)
    if not m:
        raise ValueError(f"{m} has unsupported version")
    return (int(m.group(1)), int(m.group(2) or 0))


ROOT = pathlib.Path(__file__).resolve().parent
TOOLCHAINS = [p.stem for p in (ROOT / "envs").iterdir() if p.suffix == ".json"]
TOOLCHAINS.sort(key=msvc_sort_key)

ARCH_ALIASES = {
    "x86": ("x86", ),
    "x64": ("x64", "amd64", ),
}

def match_arch_argument(name: str, host: str, target: str) -> str:
    return textwrap.dedent(f"""\
        if /I "%1"=="{name}" (
            set __VCVARSALL_HOST_ARCH={host}
            set __VCVARSALL_TARGET_ARCH={target}
            set __local_ARG_FOUND=1
        )
    """)


def path_list_to_cmd_variable(rel_paths: list[str]) -> str:
    result = ";".join("%__MSVC_ROOT%\\" + p.replace("/", "\\") for p in rel_paths)
    return result


def main():
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument("--toolchain", choices=TOOLCHAINS, required=True, help="MSVC toolchain version")
    parser.add_argument("location", type=pathlib.Path, default=pathlib.Path.cwd(), nargs="?",help="Directory")
    args = parser.parse_args()

    with (ROOT / "envs" / f"{args.toolchain}.json").open("r") as f:
        toolchain_json = json.load(f)

    vcvars_dir_path = args.location / "VC/Auxiliary/Build"
    vcvarsall_path = vcvars_dir_path / "vcvarsall.bat"
    vcvarsall_path.parent.mkdir(exist_ok=True, parents=True)

    archs = {host_arch: list(toolchain_json["compiler-paths"]["host"][host_arch]["target"].keys()) for host_arch in toolchain_json["compiler-paths"]["host"].keys()}

    detect_arch_arg = textwrap.dedent("""\
        @rem Architecture
        set __local_ARG_FOUND=
    """)

    for host_arch, target_archs in archs.items():
        for target_arch in target_archs:
            if host_arch == target_arch:
                for arch_alias in ARCH_ALIASES[host_arch]:
                    detect_arch_arg += match_arch_argument(
                        name=arch_alias,
                        host=host_arch,
                        target=target_arch,
                    )
            else:
                for host_arch_alias in ARCH_ALIASES[host_arch]:
                    for target_arch_alias in ARCH_ALIASES[target_arch]:
                        detect_arch_arg += match_arch_argument(
                            name=f"{host_arch_alias}_{target_arch_alias}",
                            host=host_arch,
                            target=target_arch,
                        )
    if "x64" not in archs and "x86" in archs:
        detect_arch_arg += "rem Fake x64 support for CLion\n"
        detect_arch_arg += match_arch_argument(
            name="amd64",
            host="x86",
            target="x86",
        )

    set_env = ""
    for host_arch, host_arch_paths in toolchain_json["compiler-paths"]["host"].items():
        set_env += f"""if /I "%__VCVARSALL_HOST_ARCH%"=="{host_arch}" (\n"""
        for target_arch, host_target_paths in host_arch_paths["target"].items():
            host_target_bat_filename = f"setupvc_{host_arch}_{target_arch}.bat"
            env_path = host_target_paths.get("path", []) + toolchain_json["sdk-paths"]["target"][host_arch].get("path", [])
            env_include = toolchain_json["sdk-paths"]["target"][target_arch].get("include", [])
            env_lib = toolchain_json["sdk-paths"]["target"][target_arch].get("lib", [])
            with (vcvars_dir_path / host_target_bat_filename).open("w", newline="\n") as f:
                f.write(f"""@echo off\n""")
                f.write(f"""\n""")
                f.write(f"""set __MSVC_ROOT=%~dp0..\\..\\..\n""")
                f.write(f"""for %%i in ("%__MSVC_ROOT%") do SET "__MSVC_ROOT=%%~fi"\n""")
                f.write(f"""set PATH={path_list_to_cmd_variable(env_path)};%PATH%\n""")
                f.write(f"""set INCLUDE={path_list_to_cmd_variable(env_include)};%INCLUDE%\n""")
                f.write(f"""set LIB={path_list_to_cmd_variable(env_lib)};%LIB%\n""")

            set_env += f"""    if /I "%__VCVARSALL_TARGET_ARCH%"=="{target_arch}" (\n"""
            set_env += f"""        echo [vcvarsall.bat] Activating environment for host={host_arch} target={target_arch}\n"""
            set_env += f"""        call "%__MSVC_ROOT%\\VC\\Auxiliary\\Build\\{host_target_bat_filename}"\n"""

            set_env += f"""    )\n"""
        set_env += ")\n"

    msvc_version = toolchain_json["version"]

    vcvarsall_contents = textwrap.dedent(f"""
        @echo off
        
        rem This file is autogenerated. Changes will be lost.

        set __MSVC_ROOT=%~dp0..\\..\\..
        for %%i in ("%__MSVC_ROOT%") do SET "__MSVC_ROOT=%%~fi"
        set __VCVARSALL_HOST_ARCH=
        set __VCVARSALL_TARGET_ARCH=
        set __VCVARSALL_PARSE_ERROR=0
        set "__VCVARSALL_ARGS_LIST=%*"
        
        call :parse_loop

        if "%__VCVARSALL_PARSE_ERROR%" NEQ "0" goto :usage_error
        if "%__VCVARSALL_TARGET_ARCH%" == "" goto :usage_error
        if "%__VCVARSALL_HOST_ARCH%" == "" goto :usage_error
        
    """) + set_env + textwrap.dedent(f"""
        set VisualStudioVersion={msvc_version}
        goto :end
        
        :parse_loop
        for /F "tokens=1,* delims= " %%a in ("%__VCVARSALL_ARGS_LIST%") do (
            call :parse_argument %%a
            set "__VCVARSALL_ARGS_LIST=%%b"
            goto :parse_loop
        )
        exit /B 0
        
        :parse_argument
    """) + detect_arch_arg + textwrap.dedent(f"""
        
        if "%__local_ARG_FOUND%" NEQ "1" (
            set /A __VCVARSALL_PARSE_ERROR=__VCVARSALL_PARSE_ERROR+1
            if "%2"=="" (
                @echo [ERROR:%~nx0] Invalid argument found : %1
            ) else (
                @echo [ERROR:%~nx0] Invalid argument found : %1=%2
            )
        )
        set __local_ARG_FOUND=
        exit /B 0
        :usage_error
        echo [ERROR:%~nx0] Error in script usage.
        goto :end
        
        :end
        set __MSVC_ROOT=
        set __VCVARSALL_HOST_ARCH=
        set __VCVARSALL_TARGET_ARCH=
        set __VCVARSALL_PARSE_ERROR=
        set "__VCVARSALL_ARGS_LIST=
    """)

    with vcvarsall_path.open("w", newline="\n") as f:
        f.write(vcvarsall_contents)


if __name__ == "__main__":
    raise SystemExit(main())
