#!/usr/bin/env python

import argparse
import json
import os
import pathlib
import platform
import re
import shutil
import stat
import textwrap


RE_MSVC_VERSION = re.compile(r"msvc([0-9]+)[^0-9]*([0-9]+)?\S*")

def msvc_sort_key(v: str) -> (int, int):
    m = RE_MSVC_VERSION.match(v)
    if not m:
        raise ValueError(f"{m} has unsupported version")
    return (int(m.group(1)), int(m.group(2) or 0))


ROOT = pathlib.Path(__file__).resolve().parent
TOOLCHAINS = [p.stem for p in (ROOT / "envs").iterdir() if p.suffix == ".json"]
TOOLCHAINS.sort(key=msvc_sort_key)

def copy_shell_script(src: pathlib.Path, dst: pathlib.Path):
    shutil.copy(src, dst)
    dst.chmod(stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)

def main():
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument("--toolchain", choices=TOOLCHAINS, required=True, help="MSVC toolchain version")
    parser.add_argument("--real-mt", action="store_true", dest="real_mt", help="Use real MT.EXE (only for MSVC8+)")
    parser.add_argument("location", type=pathlib.Path, default=pathlib.Path.cwd(), nargs="?",help="Directory")
    args = parser.parse_args()

    available_wrappers = list(p.stem.lower() for p in (ROOT / "wrappers/bin").iterdir() if p.is_file())
    available_wrappers.sort()

    if platform.system() in ("Windows", "Java"):
        parser.error(f"Unsupported platform ({platform.system()})")
        return 1

    shutil.rmtree(args.location / "wine", ignore_errors=True)
    (args.location / "activate").unlink(missing_ok=True)

    with (ROOT / "envs" / f"{args.toolchain}.json").open("r") as f:
        toolchain_json = json.load(f)

    set_available_wrappers = set(available_wrappers)
    msvc_bins = {}
    for root, _, filenames in args.location.walk():
        for filename in filenames:
            lfilename = pathlib.Path(filename.lower())
            if lfilename.suffix == ".exe" and lfilename.stem in set_available_wrappers and lfilename.stem not in toolchain_json["conflict"]:
                new_path = root / filename
                if lfilename.stem in msvc_bins:
                    raise ValueError(f"Duplicate executable for {lfilename}: \"{msvc_bins[lfilename.stem]}\" and \"{new_path}\"")
                msvc_bins[lfilename.stem] = new_path

    for stem, relpath in toolchain_json["conflict"].items():
        bin_path = args.location / relpath
        if not bin_path.is_file():
            raise ValueError(f"conflict {stem} \"{bin_path}\" does not exist")
        msvc_bins[stem] = bin_path

    def create_env_content(paths):
        return ";".join("${MSVC_ROOT}\\\\" + p.replace("/", "\\\\") for p in paths)

    env_winepath = create_env_content(toolchain_json["winepath"])
    env_include = create_env_content(toolchain_json["include"])
    env_lib = create_env_content(toolchain_json["lib"])

    (args.location / "wine/bin").mkdir(parents=True)

    copy_shell_script(ROOT / "wrappers/wine-msvc.sh", args.location / "wine")

    with (args.location / "wine/msvcenv.sh").open("w", newline="\n") as f_env:
        f_env.write(textwrap.dedent(f"""
            #!/usr/bin/env bash
            #
            # Copyright (c) 2018 Martin Storsjo
            # Copyright (c) 2025 archaic-msvc developers
            #
            # Permission to use, copy, modify, and/or distribute this software for any
            # purpose with or without fee is hereby granted, provided that the above
            # copyright notice and this permission notice appear in all copies.
            #
            # THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
            # WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
            # MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
            # ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
            # WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
            # ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
            # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
            
            set -e
            
            # This file is autogenerated. Changes will be lost.
            
            MSVC_ROOT="$(cd -- "$(dirname -- "$0")/../.." && printf '%s\\n' "$(pwd)")"
            MSVC_ROOT=${{MSVC_ROOT//\\//\\\\}}
            export INCLUDE="{env_include}"
            export LIB="{env_lib}"
            export LIBPATH="$LIB"
            export WINEPATH="{env_winepath}"
        """))
        f_env.write("\n")
        for bin_stem in available_wrappers:
            if not bin_stem in msvc_bins:
                continue
            bin_path = msvc_bins[bin_stem]
            relative_location = str(bin_path.relative_to(args.location)).replace("/", "\\\\")
            f_env.write(f"MSVC_{bin_stem.upper()}_BIN=\"${{MSVC_ROOT}}\\\\{relative_location}\"\n")

            copy_shell_script(ROOT / "wrappers/bin" / bin_stem, args.location / "wine/bin" / bin_stem)
            os.symlink(bin_stem, args.location / f"wine/bin/{bin_stem}.exe")

    if args.real_mt and "mt" in msvc_bins:
        dst_mt = args.location / "wine/bin/mt"
        dst_mt.unlink()
        copy_shell_script(ROOT / "wrappers/misc/mt", dst_mt)


    with (args.location / "activate").open("w", newline="\n") as f_activate:
        f_activate.write(textwrap.dedent(f"""
            # This file must be used with "source bin/activate" *from bash*
            # You cannot run it directly
            
            # This file is autogenerated. Changes will be lost.
            
            if test "x$BASH_SOURCE" = x; then
                echo "Unsupported shell" >2
                exit 1
            fi
            
            export PATH="$(cd -- "$(dirname -- "$BASH_SOURCE")" && printf '%s\\n' "$(pwd)")/wine/bin:$PATH"
            
            echo "{args.toolchain} is now available"
        """))


if __name__ == "__main__":
    raise SystemExit(main())
